/*
-- Query: SELECT * FROM nextreview.team
LIMIT 0, 10000

-- Date: 2017-07-16 14:30
*/
INSERT INTO `team` (`id`,`name`) VALUES (1,'Resourcepool Web');
INSERT INTO `team` (`id`,`name`) VALUES (2,'Resourcepool Core');
INSERT INTO `team` (`id`,`name`) VALUES (3,'Resourcepool DevOps');
INSERT INTO `team` (`id`,`name`) VALUES (4,'Deadlock Web');
INSERT INTO `team` (`id`,`name`) VALUES (5,'Deadlock API');
INSERT INTO `team` (`id`,`name`) VALUES (6,'Deadlock QA');
INSERT INTO `team` (`id`,`name`) VALUES (7,'FireFighters');
INSERT INTO `team` (`id`,`name`) VALUES (8,'Interns');
INSERT INTO `team` (`id`,`name`) VALUES (9,'Sagittis felis. Donec tempor,');
INSERT INTO `team` (`id`,`name`) VALUES (10,'Eleifend. Cras sed');
INSERT INTO `team` (`id`,`name`) VALUES (11,'Vitae, posuere at,');
INSERT INTO `team` (`id`,`name`) VALUES (12,'Sit amet luctus');
INSERT INTO `team` (`id`,`name`) VALUES (13,'Adipiscing non, luctus');
INSERT INTO `team` (`id`,`name`) VALUES (14,'Cras eget nisi dictum');
INSERT INTO `team` (`id`,`name`) VALUES (15,'Sed id risus quis');
INSERT INTO `team` (`id`,`name`) VALUES (16,'Aliquam nisl. Nulla');
INSERT INTO `team` (`id`,`name`) VALUES (17,'Phasellus dolor elit, pellentesque');
INSERT INTO `team` (`id`,`name`) VALUES (18,'Facilisis lorem tristique aliquet.');
INSERT INTO `team` (`id`,`name`) VALUES (19,'Nec, cursus a, enim.');
INSERT INTO `team` (`id`,`name`) VALUES (20,'Et netus et malesuada');
INSERT INTO `team` (`id`,`name`) VALUES (21,'Dignissim magna a tortor.');
INSERT INTO `team` (`id`,`name`) VALUES (22,'Gravida sit amet,');
INSERT INTO `team` (`id`,`name`) VALUES (23,'Mauris blandit mattis.');
INSERT INTO `team` (`id`,`name`) VALUES (24,'In lorem. Donec elementum,');
INSERT INTO `team` (`id`,`name`) VALUES (25,'Ac turpis egestas.');
INSERT INTO `team` (`id`,`name`) VALUES (26,'Fermentum convallis ligula.');
INSERT INTO `team` (`id`,`name`) VALUES (27,'Dui. Cum sociis natoque');
INSERT INTO `team` (`id`,`name`) VALUES (28,'Interdum enim non');
INSERT INTO `team` (`id`,`name`) VALUES (29,'Neque venenatis lacus.');
INSERT INTO `team` (`id`,`name`) VALUES (30,'Dignissim pharetra. Nam');
INSERT INTO `team` (`id`,`name`) VALUES (31,'Volutpat. Nulla dignissim. Maecenas');
INSERT INTO `team` (`id`,`name`) VALUES (32,'Duis risus odio,');
INSERT INTO `team` (`id`,`name`) VALUES (33,'Aenean euismod mauris eu');
INSERT INTO `team` (`id`,`name`) VALUES (34,'Magna. Phasellus dolor elit,');
INSERT INTO `team` (`id`,`name`) VALUES (35,'Lorem lorem, luctus ut,');
INSERT INTO `team` (`id`,`name`) VALUES (36,'Luctus, ipsum leo');
INSERT INTO `team` (`id`,`name`) VALUES (37,'Elementum at, egestas');
INSERT INTO `team` (`id`,`name`) VALUES (38,'Orci. Donec nibh. Quisque');
INSERT INTO `team` (`id`,`name`) VALUES (39,'Convallis dolor. Quisque tincidunt');
INSERT INTO `team` (`id`,`name`) VALUES (40,'Lacinia mattis. Integer eu');
INSERT INTO `team` (`id`,`name`) VALUES (41,'Hendrerit a, arcu. Sed');
INSERT INTO `team` (`id`,`name`) VALUES (42,'Molestie arcu. Sed');
INSERT INTO `team` (`id`,`name`) VALUES (43,'Tincidunt pede ac');
INSERT INTO `team` (`id`,`name`) VALUES (44,'Erat semper rutrum.');
INSERT INTO `team` (`id`,`name`) VALUES (45,'Donec non justo. Proin');
INSERT INTO `team` (`id`,`name`) VALUES (46,'Sem mollis dui,');
INSERT INTO `team` (`id`,`name`) VALUES (47,'Ligula. Nullam feugiat');
INSERT INTO `team` (`id`,`name`) VALUES (48,'Nascetur ridiculus mus. Proin');
INSERT INTO `team` (`id`,`name`) VALUES (49,'Ac turpis egestas. Aliquam');
INSERT INTO `team` (`id`,`name`) VALUES (50,'Proin non massa');
INSERT INTO `team` (`id`,`name`) VALUES (51,'Sem. Nulla interdum.');
INSERT INTO `team` (`id`,`name`) VALUES (52,'At pede. Cras');
INSERT INTO `team` (`id`,`name`) VALUES (53,'Luctus vulputate, nisi sem');
INSERT INTO `team` (`id`,`name`) VALUES (54,'Hendrerit. Donec porttitor');
INSERT INTO `team` (`id`,`name`) VALUES (55,'Nam ac nulla. In');
INSERT INTO `team` (`id`,`name`) VALUES (56,'Ac turpis egestas. Fusce');
INSERT INTO `team` (`id`,`name`) VALUES (57,'Eu turpis. Nulla aliquet.');
INSERT INTO `team` (`id`,`name`) VALUES (58,'Convallis convallis dolor. Quisque');
INSERT INTO `team` (`id`,`name`) VALUES (59,'Lacus pede sagittis');
INSERT INTO `team` (`id`,`name`) VALUES (60,'Amet ante. Vivamus non');
INSERT INTO `team` (`id`,`name`) VALUES (61,'Quisque varius. Nam');
INSERT INTO `team` (`id`,`name`) VALUES (62,'Ultrices posuere cubilia Curae');
INSERT INTO `team` (`id`,`name`) VALUES (63,'Nullam velit dui,');
INSERT INTO `team` (`id`,`name`) VALUES (64,'Suspendisse ac metus');
INSERT INTO `team` (`id`,`name`) VALUES (65,'Nonummy ipsum non arcu.');
INSERT INTO `team` (`id`,`name`) VALUES (66,'Massa. Vestibulum accumsan neque');
INSERT INTO `team` (`id`,`name`) VALUES (67,'Arcu. Nunc mauris.');
INSERT INTO `team` (`id`,`name`) VALUES (68,'Dolor elit, pellentesque');
INSERT INTO `team` (`id`,`name`) VALUES (69,'Gravida. Praesent eu');
INSERT INTO `team` (`id`,`name`) VALUES (70,'Mattis. Cras eget nisi');
INSERT INTO `team` (`id`,`name`) VALUES (71,'Arcu. Vivamus sit');
INSERT INTO `team` (`id`,`name`) VALUES (72,'Bibendum ullamcorper. Duis');
INSERT INTO `team` (`id`,`name`) VALUES (73,'Sem molestie sodales.');
INSERT INTO `team` (`id`,`name`) VALUES (74,'Risus. Quisque libero');
INSERT INTO `team` (`id`,`name`) VALUES (75,'Phasellus in felis. Nulla');
INSERT INTO `team` (`id`,`name`) VALUES (76,'Sed, hendrerit a,');
INSERT INTO `team` (`id`,`name`) VALUES (77,'Dignissim tempor arcu. Vestibulum');
INSERT INTO `team` (`id`,`name`) VALUES (78,'Enim. Nunc ut');
INSERT INTO `team` (`id`,`name`) VALUES (79,'Vulputate, nisi sem');
INSERT INTO `team` (`id`,`name`) VALUES (80,'Lacus. Nulla tincidunt, neque');
INSERT INTO `team` (`id`,`name`) VALUES (81,'Adipiscing elit. Etiam laoreet,');
INSERT INTO `team` (`id`,`name`) VALUES (82,'Vel, convallis in, cursus');
INSERT INTO `team` (`id`,`name`) VALUES (83,'Magna. Duis dignissim');
INSERT INTO `team` (`id`,`name`) VALUES (84,'Mauris vel turpis. Aliquam');
INSERT INTO `team` (`id`,`name`) VALUES (85,'Aliquam erat volutpat.');
INSERT INTO `team` (`id`,`name`) VALUES (86,'At, iaculis quis,');
INSERT INTO `team` (`id`,`name`) VALUES (87,'Quisque tincidunt pede ac');
INSERT INTO `team` (`id`,`name`) VALUES (88,'Dis parturient montes, nascetur');
INSERT INTO `team` (`id`,`name`) VALUES (89,'Vel, vulputate eu, odio.');
INSERT INTO `team` (`id`,`name`) VALUES (90,'Curabitur dictum. Phasellus in');
INSERT INTO `team` (`id`,`name`) VALUES (91,'Posuere vulputate, lacus.');
INSERT INTO `team` (`id`,`name`) VALUES (92,'Ut aliquam iaculis, lacus');
INSERT INTO `team` (`id`,`name`) VALUES (93,'Enim nec tempus scelerisque,');
INSERT INTO `team` (`id`,`name`) VALUES (94,'Quam vel sapien imperdiet');
INSERT INTO `team` (`id`,`name`) VALUES (95,'Leo, in lobortis tellus');
INSERT INTO `team` (`id`,`name`) VALUES (96,'Cras dolor dolor,');
INSERT INTO `team` (`id`,`name`) VALUES (97,'Ipsum. Suspendisse sagittis. Nullam');
INSERT INTO `team` (`id`,`name`) VALUES (98,'Sed dictum eleifend,');
INSERT INTO `team` (`id`,`name`) VALUES (99,'At fringilla purus');
INSERT INTO `team` (`id`,`name`) VALUES (100,'Mi, ac mattis velit');
INSERT INTO `team` (`id`,`name`) VALUES (101,'Dolor vitae dolor.');
INSERT INTO `team` (`id`,`name`) VALUES (102,'Quis accumsan convallis, ante');
INSERT INTO `team` (`id`,`name`) VALUES (103,'Ornare, elit elit');
INSERT INTO `team` (`id`,`name`) VALUES (104,'Mollis lectus pede');
INSERT INTO `team` (`id`,`name`) VALUES (105,'Etiam vestibulum massa');
INSERT INTO `team` (`id`,`name`) VALUES (106,'Duis ac arcu. Nunc');
INSERT INTO `team` (`id`,`name`) VALUES (107,'Enim. Sed nulla ante,');
INSERT INTO `team` (`id`,`name`) VALUES (108,'Tellus sem mollis');
INSERT INTO `team` (`id`,`name`) VALUES (109,'Luctus vulputate, nisi');
INSERT INTO `team` (`id`,`name`) VALUES (110,'Vivamus nibh dolor, nonummy');
INSERT INTO `team` (`id`,`name`) VALUES (111,'Integer tincidunt aliquam');
INSERT INTO `team` (`id`,`name`) VALUES (112,'Aliquet vel, vulputate');
INSERT INTO `team` (`id`,`name`) VALUES (113,'Ridiculus mus. Proin');
INSERT INTO `team` (`id`,`name`) VALUES (114,'Magna et ipsum');
INSERT INTO `team` (`id`,`name`) VALUES (115,'Nulla at sem molestie');
INSERT INTO `team` (`id`,`name`) VALUES (116,'Erat volutpat. Nulla');
INSERT INTO `team` (`id`,`name`) VALUES (117,'Justo. Praesent luctus.');
INSERT INTO `team` (`id`,`name`) VALUES (118,'Ac mattis semper,');
INSERT INTO `team` (`id`,`name`) VALUES (119,'Suspendisse commodo tincidunt nibh.');
INSERT INTO `team` (`id`,`name`) VALUES (120,'Diam vel arcu. Curabitur');
INSERT INTO `team` (`id`,`name`) VALUES (121,'Scelerisque scelerisque dui.');
INSERT INTO `team` (`id`,`name`) VALUES (122,'Pharetra ut, pharetra');
INSERT INTO `team` (`id`,`name`) VALUES (123,'Fermentum vel, mauris.');
INSERT INTO `team` (`id`,`name`) VALUES (124,'Ante blandit viverra.');
INSERT INTO `team` (`id`,`name`) VALUES (125,'Vulputate, risus a');
INSERT INTO `team` (`id`,`name`) VALUES (126,'Vivamus non lorem');
INSERT INTO `team` (`id`,`name`) VALUES (127,'Fringilla cursus purus.');
INSERT INTO `team` (`id`,`name`) VALUES (128,'Arcu. Aliquam ultrices iaculis');
INSERT INTO `team` (`id`,`name`) VALUES (129,'Ipsum dolor sit amet,');
INSERT INTO `team` (`id`,`name`) VALUES (130,'Mauris, rhoncus id,');
INSERT INTO `team` (`id`,`name`) VALUES (131,'Viverra. Maecenas iaculis aliquet');
INSERT INTO `team` (`id`,`name`) VALUES (132,'Nullam ut nisi');
INSERT INTO `team` (`id`,`name`) VALUES (133,'Libero dui nec');
INSERT INTO `team` (`id`,`name`) VALUES (134,'Urna. Vivamus molestie');
INSERT INTO `team` (`id`,`name`) VALUES (135,'Suspendisse sed dolor. Fusce');
INSERT INTO `team` (`id`,`name`) VALUES (136,'In consectetuer ipsum');
INSERT INTO `team` (`id`,`name`) VALUES (137,'Rutrum. Fusce dolor');
INSERT INTO `team` (`id`,`name`) VALUES (138,'Nec ligula consectetuer');
INSERT INTO `team` (`id`,`name`) VALUES (139,'Risus odio, auctor vitae,');
INSERT INTO `team` (`id`,`name`) VALUES (140,'Enim, condimentum eget,');
INSERT INTO `team` (`id`,`name`) VALUES (141,'Nulla magna, malesuada vel,');
INSERT INTO `team` (`id`,`name`) VALUES (142,'Lectus convallis est, vitae');
INSERT INTO `team` (`id`,`name`) VALUES (143,'Pretium neque. Morbi quis');
INSERT INTO `team` (`id`,`name`) VALUES (144,'Sed congue, elit');
INSERT INTO `team` (`id`,`name`) VALUES (145,'Vel nisl. Quisque');
INSERT INTO `team` (`id`,`name`) VALUES (146,'Quam vel sapien');
INSERT INTO `team` (`id`,`name`) VALUES (147,'Dolor. Quisque tincidunt pede');
INSERT INTO `team` (`id`,`name`) VALUES (148,'Iaculis enim, sit amet');
INSERT INTO `team` (`id`,`name`) VALUES (149,'Consectetuer euismod est arcu');
INSERT INTO `team` (`id`,`name`) VALUES (150,'Etiam ligula tortor,');
INSERT INTO `team` (`id`,`name`) VALUES (151,'Penatibus et magnis');
INSERT INTO `team` (`id`,`name`) VALUES (152,'Lorem, luctus ut,');
INSERT INTO `team` (`id`,`name`) VALUES (153,'Ullamcorper magna. Sed eu');
INSERT INTO `team` (`id`,`name`) VALUES (154,'Felis. Donec tempor,');
INSERT INTO `team` (`id`,`name`) VALUES (155,'Egestas nunc sed');
INSERT INTO `team` (`id`,`name`) VALUES (156,'Erat, in consectetuer ipsum');
INSERT INTO `team` (`id`,`name`) VALUES (157,'Lectus quis massa. Mauris');
INSERT INTO `team` (`id`,`name`) VALUES (158,'Euismod urna. Nullam lobortis');
INSERT INTO `team` (`id`,`name`) VALUES (159,'Ac nulla. In tincidunt');
INSERT INTO `team` (`id`,`name`) VALUES (160,'Eu, ultrices sit');
INSERT INTO `team` (`id`,`name`) VALUES (161,'Pede, nonummy ut, molestie');
INSERT INTO `team` (`id`,`name`) VALUES (162,'Metus vitae velit egestas');
INSERT INTO `team` (`id`,`name`) VALUES (163,'At, libero. Morbi accumsan');
INSERT INTO `team` (`id`,`name`) VALUES (164,'Elit elit fermentum risus,');
INSERT INTO `team` (`id`,`name`) VALUES (165,'Enim diam vel arcu.');
INSERT INTO `team` (`id`,`name`) VALUES (166,'Cum sociis natoque');
INSERT INTO `team` (`id`,`name`) VALUES (167,'Neque venenatis lacus. Etiam');
INSERT INTO `team` (`id`,`name`) VALUES (168,'Elit sed consequat');
INSERT INTO `team` (`id`,`name`) VALUES (169,'Integer vulputate, risus a');
INSERT INTO `team` (`id`,`name`) VALUES (170,'Et, rutrum eu,');
INSERT INTO `team` (`id`,`name`) VALUES (171,'Nam porttitor scelerisque');
INSERT INTO `team` (`id`,`name`) VALUES (172,'Libero. Proin mi.');
INSERT INTO `team` (`id`,`name`) VALUES (173,'Ultricies adipiscing, enim');
INSERT INTO `team` (`id`,`name`) VALUES (174,'Morbi sit amet massa.');
INSERT INTO `team` (`id`,`name`) VALUES (175,'Sed dolor. Fusce mi');
INSERT INTO `team` (`id`,`name`) VALUES (176,'Accumsan laoreet ipsum.');
INSERT INTO `team` (`id`,`name`) VALUES (177,'Felis. Nulla tempor augue');
INSERT INTO `team` (`id`,`name`) VALUES (178,'Vitae erat vel');
INSERT INTO `team` (`id`,`name`) VALUES (179,'Amet, faucibus ut,');
INSERT INTO `team` (`id`,`name`) VALUES (180,'Quis massa. Mauris vestibulum,');
INSERT INTO `team` (`id`,`name`) VALUES (181,'Mauris, rhoncus id, mollis');
INSERT INTO `team` (`id`,`name`) VALUES (182,'Donec tempus, lorem fringilla');
INSERT INTO `team` (`id`,`name`) VALUES (183,'Mauris. Morbi non');
INSERT INTO `team` (`id`,`name`) VALUES (184,'Penatibus et magnis dis');
INSERT INTO `team` (`id`,`name`) VALUES (185,'Ornare. Fusce mollis.');
INSERT INTO `team` (`id`,`name`) VALUES (186,'Arcu et pede.');
INSERT INTO `team` (`id`,`name`) VALUES (187,'Mauris non dui nec');
INSERT INTO `team` (`id`,`name`) VALUES (188,'Vestibulum, neque sed dictum');
INSERT INTO `team` (`id`,`name`) VALUES (189,'Duis dignissim tempor arcu.');
INSERT INTO `team` (`id`,`name`) VALUES (190,'Aliquam ornare, libero');
INSERT INTO `team` (`id`,`name`) VALUES (191,'Et netus et');
INSERT INTO `team` (`id`,`name`) VALUES (192,'Porttitor scelerisque neque. Nullam');
INSERT INTO `team` (`id`,`name`) VALUES (193,'Eu lacus. Quisque imperdiet,');
INSERT INTO `team` (`id`,`name`) VALUES (194,'Aliquam auctor, velit eget');
INSERT INTO `team` (`id`,`name`) VALUES (195,'Venenatis lacus. Etiam');
INSERT INTO `team` (`id`,`name`) VALUES (196,'Nisi. Aenean eget metus.');
INSERT INTO `team` (`id`,`name`) VALUES (197,'Ut tincidunt vehicula risus.');
INSERT INTO `team` (`id`,`name`) VALUES (198,'Tellus sem mollis dui,');
INSERT INTO `team` (`id`,`name`) VALUES (199,'Metus. In lorem.');
INSERT INTO `team` (`id`,`name`) VALUES (200,'Nunc. Quisque ornare tortor');
INSERT INTO `team` (`id`,`name`) VALUES (201,'Egestas. Sed pharetra, felis');
INSERT INTO `team` (`id`,`name`) VALUES (202,'Et magnis dis parturient');
INSERT INTO `team` (`id`,`name`) VALUES (203,'Amet ultricies sem');
INSERT INTO `team` (`id`,`name`) VALUES (204,'Sed, est. Nunc laoreet');
INSERT INTO `team` (`id`,`name`) VALUES (205,'Nibh. Phasellus nulla. Integer');
INSERT INTO `team` (`id`,`name`) VALUES (206,'Quis lectus. Nullam');
INSERT INTO `team` (`id`,`name`) VALUES (207,'Enim, gravida sit');
INSERT INTO `team` (`id`,`name`) VALUES (208,'Nunc nulla vulputate');
INSERT INTO `team` (`id`,`name`) VALUES (209,'Sapien, gravida non, sollicitudin');
INSERT INTO `team` (`id`,`name`) VALUES (210,'Nec, imperdiet nec, leo.');
INSERT INTO `team` (`id`,`name`) VALUES (211,'Lorem, eget mollis');
INSERT INTO `team` (`id`,`name`) VALUES (212,'Mauris molestie pharetra');
INSERT INTO `team` (`id`,`name`) VALUES (213,'Ligula. Aliquam erat');
INSERT INTO `team` (`id`,`name`) VALUES (214,'Eleifend egestas. Sed');
INSERT INTO `team` (`id`,`name`) VALUES (215,'Risus. Quisque libero lacus,');
INSERT INTO `team` (`id`,`name`) VALUES (216,'Nulla eget metus eu');
INSERT INTO `team` (`id`,`name`) VALUES (217,'Amet diam eu dolor');
INSERT INTO `team` (`id`,`name`) VALUES (218,'Tempor erat neque non');
INSERT INTO `team` (`id`,`name`) VALUES (219,'Ligula consectetuer rhoncus. Nullam');
INSERT INTO `team` (`id`,`name`) VALUES (220,'A tortor. Nunc commodo');
INSERT INTO `team` (`id`,`name`) VALUES (221,'Egestas blandit. Nam nulla');
INSERT INTO `team` (`id`,`name`) VALUES (222,'Dui, semper et, lacinia');
INSERT INTO `team` (`id`,`name`) VALUES (223,'Consequat, lectus sit');
INSERT INTO `team` (`id`,`name`) VALUES (224,'Congue turpis. In condimentum.');
INSERT INTO `team` (`id`,`name`) VALUES (225,'Orci, consectetuer euismod est');
INSERT INTO `team` (`id`,`name`) VALUES (226,'Cursus et, eros. Proin');
INSERT INTO `team` (`id`,`name`) VALUES (227,'Eget metus. In nec');
INSERT INTO `team` (`id`,`name`) VALUES (228,'Semper, dui lectus');
INSERT INTO `team` (`id`,`name`) VALUES (229,'Ad litora torquent per');
INSERT INTO `team` (`id`,`name`) VALUES (230,'Dictum magna. Ut');
INSERT INTO `team` (`id`,`name`) VALUES (231,'Consectetuer, cursus et,');
INSERT INTO `team` (`id`,`name`) VALUES (232,'Lobortis risus. In');
INSERT INTO `team` (`id`,`name`) VALUES (233,'Risus. Donec nibh');
INSERT INTO `team` (`id`,`name`) VALUES (234,'Ornare, elit elit fermentum');
INSERT INTO `team` (`id`,`name`) VALUES (235,'Leo. Morbi neque');
INSERT INTO `team` (`id`,`name`) VALUES (236,'Tincidunt pede ac urna.');
INSERT INTO `team` (`id`,`name`) VALUES (237,'Mollis. Integer tincidunt');
INSERT INTO `team` (`id`,`name`) VALUES (238,'Molestie. Sed id');
INSERT INTO `team` (`id`,`name`) VALUES (239,'Vitae, sodales at,');
INSERT INTO `team` (`id`,`name`) VALUES (240,'Vivamus nisi. Mauris nulla.');
INSERT INTO `team` (`id`,`name`) VALUES (241,'Ante ipsum primis');
INSERT INTO `team` (`id`,`name`) VALUES (242,'Aenean egestas hendrerit');
INSERT INTO `team` (`id`,`name`) VALUES (243,'Libero at auctor');
INSERT INTO `team` (`id`,`name`) VALUES (244,'Semper auctor. Mauris');
INSERT INTO `team` (`id`,`name`) VALUES (245,'Primis in faucibus orci');
INSERT INTO `team` (`id`,`name`) VALUES (246,'Risus. Duis a mi');
INSERT INTO `team` (`id`,`name`) VALUES (247,'Pede sagittis augue,');
INSERT INTO `team` (`id`,`name`) VALUES (248,'Metus. Aliquam erat volutpat.');
INSERT INTO `team` (`id`,`name`) VALUES (249,'Ligula. Nullam enim.');
INSERT INTO `team` (`id`,`name`) VALUES (250,'Ut, molestie in, tempus');
INSERT INTO `team` (`id`,`name`) VALUES (251,'Dis parturient montes,');
INSERT INTO `team` (`id`,`name`) VALUES (252,'Arcu. Vivamus sit amet');
INSERT INTO `team` (`id`,`name`) VALUES (253,'Lorem ac risus. Morbi');
INSERT INTO `team` (`id`,`name`) VALUES (254,'Enim non nisi. Aenean');
INSERT INTO `team` (`id`,`name`) VALUES (255,'Eget massa. Suspendisse');
INSERT INTO `team` (`id`,`name`) VALUES (256,'Luctus et ultrices');
INSERT INTO `team` (`id`,`name`) VALUES (257,'Tincidunt vehicula risus. Nulla');
INSERT INTO `team` (`id`,`name`) VALUES (258,'Sit amet metus.');
INSERT INTO `team` (`id`,`name`) VALUES (259,'Egestas hendrerit neque. In');
INSERT INTO `team` (`id`,`name`) VALUES (260,'Adipiscing, enim mi tempor');
INSERT INTO `team` (`id`,`name`) VALUES (261,'Non quam. Pellentesque');
INSERT INTO `team` (`id`,`name`) VALUES (262,'Est arcu ac orci.');
INSERT INTO `team` (`id`,`name`) VALUES (263,'Magna. Ut tincidunt');
INSERT INTO `team` (`id`,`name`) VALUES (264,'Vestibulum accumsan neque');
INSERT INTO `team` (`id`,`name`) VALUES (265,'Ipsum porta elit, a');
INSERT INTO `team` (`id`,`name`) VALUES (266,'Cras lorem lorem,');
INSERT INTO `team` (`id`,`name`) VALUES (267,'Gravida sagittis. Duis');
INSERT INTO `team` (`id`,`name`) VALUES (268,'Molestie orci tincidunt');
INSERT INTO `team` (`id`,`name`) VALUES (269,'Aenean eget metus.');
INSERT INTO `team` (`id`,`name`) VALUES (270,'Feugiat placerat velit.');
INSERT INTO `team` (`id`,`name`) VALUES (271,'Nec, diam. Duis');
INSERT INTO `team` (`id`,`name`) VALUES (272,'Aliquam ultrices iaculis');
INSERT INTO `team` (`id`,`name`) VALUES (273,'Eu nulla at sem');
INSERT INTO `team` (`id`,`name`) VALUES (274,'Tincidunt orci quis lectus.');
INSERT INTO `team` (`id`,`name`) VALUES (275,'Tempor lorem, eget');
INSERT INTO `team` (`id`,`name`) VALUES (276,'Sit amet risus.');
INSERT INTO `team` (`id`,`name`) VALUES (277,'Tellus. Nunc lectus pede,');
INSERT INTO `team` (`id`,`name`) VALUES (278,'Integer mollis. Integer');
INSERT INTO `team` (`id`,`name`) VALUES (279,'Euismod et, commodo');
INSERT INTO `team` (`id`,`name`) VALUES (280,'Gravida sagittis. Duis gravida.');
INSERT INTO `team` (`id`,`name`) VALUES (281,'Quis diam luctus');
INSERT INTO `team` (`id`,`name`) VALUES (282,'Lorem fringilla ornare placerat,');
INSERT INTO `team` (`id`,`name`) VALUES (283,'Ipsum sodales purus, in');
INSERT INTO `team` (`id`,`name`) VALUES (284,'Sociosqu ad litora torquent');
INSERT INTO `team` (`id`,`name`) VALUES (285,'Dictum mi, ac');
INSERT INTO `team` (`id`,`name`) VALUES (286,'Cursus in, hendrerit');
INSERT INTO `team` (`id`,`name`) VALUES (287,'Donec at arcu.');
INSERT INTO `team` (`id`,`name`) VALUES (288,'Curae Phasellus ornare. Fusce');
INSERT INTO `team` (`id`,`name`) VALUES (289,'Duis mi enim,');
INSERT INTO `team` (`id`,`name`) VALUES (290,'Ipsum. Suspendisse non');
INSERT INTO `team` (`id`,`name`) VALUES (291,'Felis ullamcorper viverra.');
INSERT INTO `team` (`id`,`name`) VALUES (292,'Nulla facilisi. Sed neque.');
INSERT INTO `team` (`id`,`name`) VALUES (293,'Ornare, facilisis eget,');
INSERT INTO `team` (`id`,`name`) VALUES (294,'Tempor diam dictum sapien.');
INSERT INTO `team` (`id`,`name`) VALUES (295,'Sit amet, dapibus');
INSERT INTO `team` (`id`,`name`) VALUES (296,'Proin vel arcu eu');
INSERT INTO `team` (`id`,`name`) VALUES (297,'Ultricies ligula. Nullam');
INSERT INTO `team` (`id`,`name`) VALUES (298,'Pharetra ut, pharetra sed,');
INSERT INTO `team` (`id`,`name`) VALUES (299,'Cursus a, enim. Suspendisse');
INSERT INTO `team` (`id`,`name`) VALUES (300,'Blandit viverra. Donec');
INSERT INTO `team` (`id`,`name`) VALUES (301,'Luctus lobortis. Class aptent');
INSERT INTO `team` (`id`,`name`) VALUES (302,'Consequat purus. Maecenas');
INSERT INTO `team` (`id`,`name`) VALUES (303,'Donec tempus, lorem');
INSERT INTO `team` (`id`,`name`) VALUES (304,'Vitae mauris sit amet');
INSERT INTO `team` (`id`,`name`) VALUES (305,'Tincidunt dui augue');
INSERT INTO `team` (`id`,`name`) VALUES (306,'Quis massa. Mauris');
INSERT INTO `team` (`id`,`name`) VALUES (307,'Vulputate, nisi sem semper');
INSERT INTO `team` (`id`,`name`) VALUES (308,'Tristique aliquet. Phasellus');
INSERT INTO `team` (`id`,`name`) VALUES (309,'Sed dolor. Fusce');
INSERT INTO `team` (`id`,`name`) VALUES (310,'Duis at lacus.');
INSERT INTO `team` (`id`,`name`) VALUES (311,'Venenatis lacus. Etiam bibendum');
INSERT INTO `team` (`id`,`name`) VALUES (312,'Scelerisque dui. Suspendisse ac');
INSERT INTO `team` (`id`,`name`) VALUES (313,'Orci luctus et ultrices');
INSERT INTO `team` (`id`,`name`) VALUES (314,'Aliquam adipiscing lacus. Ut');
INSERT INTO `team` (`id`,`name`) VALUES (315,'Pellentesque ut ipsum ac');
INSERT INTO `team` (`id`,`name`) VALUES (316,'Mus. Aenean eget magna.');
INSERT INTO `team` (`id`,`name`) VALUES (317,'Leo elementum sem, vitae');
INSERT INTO `team` (`id`,`name`) VALUES (318,'A tortor. Nunc');
INSERT INTO `team` (`id`,`name`) VALUES (319,'Ligula. Aenean gravida nunc');
INSERT INTO `team` (`id`,`name`) VALUES (320,'Scelerisque scelerisque dui. Suspendisse');
INSERT INTO `team` (`id`,`name`) VALUES (321,'Curabitur ut odio vel');
INSERT INTO `team` (`id`,`name`) VALUES (322,'Nec quam. Curabitur vel');
INSERT INTO `team` (`id`,`name`) VALUES (323,'Donec at arcu. Vestibulum');
INSERT INTO `team` (`id`,`name`) VALUES (324,'Nonummy ac, feugiat');
INSERT INTO `team` (`id`,`name`) VALUES (325,'Ut sagittis lobortis mauris.');
INSERT INTO `team` (`id`,`name`) VALUES (326,'Lacus, varius et,');
INSERT INTO `team` (`id`,`name`) VALUES (327,'Accumsan neque et nunc.');
INSERT INTO `team` (`id`,`name`) VALUES (328,'Venenatis a, magna.');
INSERT INTO `team` (`id`,`name`) VALUES (329,'Dignissim. Maecenas ornare egestas');
INSERT INTO `team` (`id`,`name`) VALUES (330,'Et magnis dis');
INSERT INTO `team` (`id`,`name`) VALUES (331,'Eget magna. Suspendisse tristique');
INSERT INTO `team` (`id`,`name`) VALUES (332,'Auctor odio a purus.');
INSERT INTO `team` (`id`,`name`) VALUES (333,'Lorem, auctor quis, tristique');
INSERT INTO `team` (`id`,`name`) VALUES (334,'Facilisis. Suspendisse commodo tincidunt');
INSERT INTO `team` (`id`,`name`) VALUES (335,'Luctus, ipsum leo elementum');
INSERT INTO `team` (`id`,`name`) VALUES (336,'Faucibus ut, nulla. Cras');
INSERT INTO `team` (`id`,`name`) VALUES (337,'Semper rutrum. Fusce');
INSERT INTO `team` (`id`,`name`) VALUES (338,'Erat vel pede blandit');
INSERT INTO `team` (`id`,`name`) VALUES (339,'Tempor augue ac ipsum.');
INSERT INTO `team` (`id`,`name`) VALUES (340,'Feugiat tellus lorem');
INSERT INTO `team` (`id`,`name`) VALUES (341,'Semper et, lacinia');
INSERT INTO `team` (`id`,`name`) VALUES (342,'Velit dui, semper');
INSERT INTO `team` (`id`,`name`) VALUES (343,'Mauris eu elit. Nulla');
INSERT INTO `team` (`id`,`name`) VALUES (344,'Ligula. Donec luctus');
INSERT INTO `team` (`id`,`name`) VALUES (345,'Vitae purus gravida sagittis.');
INSERT INTO `team` (`id`,`name`) VALUES (346,'Vel arcu. Curabitur ut');
INSERT INTO `team` (`id`,`name`) VALUES (347,'Sagittis felis. Donec');
INSERT INTO `team` (`id`,`name`) VALUES (348,'Quis lectus. Nullam suscipit,');
INSERT INTO `team` (`id`,`name`) VALUES (349,'Feugiat. Sed nec');
INSERT INTO `team` (`id`,`name`) VALUES (350,'Rutrum eu, ultrices');
INSERT INTO `team` (`id`,`name`) VALUES (351,'Lorem, auctor quis,');
INSERT INTO `team` (`id`,`name`) VALUES (352,'Ullamcorper, velit in');
INSERT INTO `team` (`id`,`name`) VALUES (353,'Libero mauris, aliquam eu,');
INSERT INTO `team` (`id`,`name`) VALUES (354,'Lorem ipsum sodales');
INSERT INTO `team` (`id`,`name`) VALUES (355,'Vitae sodales nisi magna');
INSERT INTO `team` (`id`,`name`) VALUES (356,'Consectetuer adipiscing elit.');
INSERT INTO `team` (`id`,`name`) VALUES (357,'Purus, in molestie tortor');
INSERT INTO `team` (`id`,`name`) VALUES (358,'Eu augue porttitor');
INSERT INTO `team` (`id`,`name`) VALUES (359,'Vivamus euismod urna.');
INSERT INTO `team` (`id`,`name`) VALUES (360,'Diam lorem, auctor quis,');
INSERT INTO `team` (`id`,`name`) VALUES (361,'Vulputate dui, nec tempus');
INSERT INTO `team` (`id`,`name`) VALUES (362,'Nulla ante, iaculis');
INSERT INTO `team` (`id`,`name`) VALUES (363,'Facilisis facilisis, magna tellus');
INSERT INTO `team` (`id`,`name`) VALUES (364,'Feugiat non, lobortis quis,');
INSERT INTO `team` (`id`,`name`) VALUES (365,'Eget ipsum. Suspendisse sagittis.');
INSERT INTO `team` (`id`,`name`) VALUES (366,'Donec egestas. Duis');
INSERT INTO `team` (`id`,`name`) VALUES (367,'Ornare, facilisis eget, ipsum.');
INSERT INTO `team` (`id`,`name`) VALUES (368,'Duis cursus, diam');
INSERT INTO `team` (`id`,`name`) VALUES (369,'Sed auctor odio');
INSERT INTO `team` (`id`,`name`) VALUES (370,'Sed eu eros. Nam');
INSERT INTO `team` (`id`,`name`) VALUES (371,'Et, rutrum eu, ultrices');
INSERT INTO `team` (`id`,`name`) VALUES (372,'Ut nec urna et');
INSERT INTO `team` (`id`,`name`) VALUES (373,'Posuere, enim nisl');
INSERT INTO `team` (`id`,`name`) VALUES (374,'Suspendisse dui. Fusce');
INSERT INTO `team` (`id`,`name`) VALUES (375,'Tempor, est ac mattis');
INSERT INTO `team` (`id`,`name`) VALUES (376,'Nunc ac mattis');
INSERT INTO `team` (`id`,`name`) VALUES (377,'Id ante dictum cursus.');
INSERT INTO `team` (`id`,`name`) VALUES (378,'In aliquet lobortis,');
INSERT INTO `team` (`id`,`name`) VALUES (379,'Integer vitae nibh.');
INSERT INTO `team` (`id`,`name`) VALUES (380,'Sit amet, consectetuer adipiscing');
INSERT INTO `team` (`id`,`name`) VALUES (381,'Tristique senectus et netus');
INSERT INTO `team` (`id`,`name`) VALUES (382,'Risus. Nunc ac sem');
INSERT INTO `team` (`id`,`name`) VALUES (383,'Aenean euismod mauris');
INSERT INTO `team` (`id`,`name`) VALUES (384,'Dignissim lacus. Aliquam rutrum');
INSERT INTO `team` (`id`,`name`) VALUES (385,'At risus. Nunc');
INSERT INTO `team` (`id`,`name`) VALUES (386,'Fusce aliquam, enim');
INSERT INTO `team` (`id`,`name`) VALUES (387,'Fringilla euismod enim. Etiam');
INSERT INTO `team` (`id`,`name`) VALUES (388,'Fames ac turpis egestas.');
INSERT INTO `team` (`id`,`name`) VALUES (389,'Magna, malesuada vel,');
INSERT INTO `team` (`id`,`name`) VALUES (390,'Cum sociis natoque penatibus');
INSERT INTO `team` (`id`,`name`) VALUES (391,'Egestas a, scelerisque sed,');
INSERT INTO `team` (`id`,`name`) VALUES (392,'Risus varius orci, in');
INSERT INTO `team` (`id`,`name`) VALUES (393,'Curae Phasellus ornare.');
INSERT INTO `team` (`id`,`name`) VALUES (394,'Amet nulla. Donec');
INSERT INTO `team` (`id`,`name`) VALUES (395,'Vel arcu eu odio');
INSERT INTO `team` (`id`,`name`) VALUES (396,'Malesuada malesuada. Integer id');
INSERT INTO `team` (`id`,`name`) VALUES (397,'Luctus et ultrices posuere');
INSERT INTO `team` (`id`,`name`) VALUES (398,'Posuere cubilia Curae Phasellus');
INSERT INTO `team` (`id`,`name`) VALUES (399,'Ligula. Donec luctus aliquet');
INSERT INTO `team` (`id`,`name`) VALUES (400,'Parturient montes, nascetur ridiculus');
INSERT INTO `team` (`id`,`name`) VALUES (401,'Orci sem eget');
INSERT INTO `team` (`id`,`name`) VALUES (402,'Nonummy. Fusce fermentum');
INSERT INTO `team` (`id`,`name`) VALUES (403,'Iaculis nec, eleifend');
INSERT INTO `team` (`id`,`name`) VALUES (404,'Non quam. Pellentesque habitant');
INSERT INTO `team` (`id`,`name`) VALUES (405,'Ut, pharetra sed, hendrerit');
INSERT INTO `team` (`id`,`name`) VALUES (406,'Quisque ac libero');
INSERT INTO `team` (`id`,`name`) VALUES (407,'Lorem semper auctor. Mauris');
INSERT INTO `team` (`id`,`name`) VALUES (408,'Orci. Phasellus dapibus quam');
INSERT INTO `team` (`id`,`name`) VALUES (409,'Neque sed dictum eleifend,');
INSERT INTO `team` (`id`,`name`) VALUES (410,'Enim, sit amet');
INSERT INTO `team` (`id`,`name`) VALUES (411,'Donec consectetuer mauris');
INSERT INTO `team` (`id`,`name`) VALUES (412,'Risus varius orci,');
INSERT INTO `team` (`id`,`name`) VALUES (413,'Rhoncus id, mollis');
INSERT INTO `team` (`id`,`name`) VALUES (414,'Interdum. Sed auctor');
INSERT INTO `team` (`id`,`name`) VALUES (415,'Nec, leo. Morbi');
INSERT INTO `team` (`id`,`name`) VALUES (416,'In nec orci.');
INSERT INTO `team` (`id`,`name`) VALUES (417,'Suspendisse commodo tincidunt');
INSERT INTO `team` (`id`,`name`) VALUES (418,'Netus et malesuada fames');
INSERT INTO `team` (`id`,`name`) VALUES (419,'Natoque penatibus et magnis');
INSERT INTO `team` (`id`,`name`) VALUES (420,'Cras convallis convallis dolor.');
INSERT INTO `team` (`id`,`name`) VALUES (421,'Mollis. Phasellus libero mauris,');
INSERT INTO `team` (`id`,`name`) VALUES (422,'Auctor vitae, aliquet nec,');
INSERT INTO `team` (`id`,`name`) VALUES (423,'Tincidunt adipiscing. Mauris');
INSERT INTO `team` (`id`,`name`) VALUES (424,'Donec nibh. Quisque nonummy');
INSERT INTO `team` (`id`,`name`) VALUES (425,'Id magna et');
INSERT INTO `team` (`id`,`name`) VALUES (426,'Nisi sem semper erat,');
INSERT INTO `team` (`id`,`name`) VALUES (427,'Lacinia. Sed congue, elit');
INSERT INTO `team` (`id`,`name`) VALUES (428,'Augue malesuada malesuada. Integer');
INSERT INTO `team` (`id`,`name`) VALUES (429,'Arcu. Vestibulum ut');
INSERT INTO `team` (`id`,`name`) VALUES (430,'Blandit at, nisi. Cum');
INSERT INTO `team` (`id`,`name`) VALUES (431,'Duis dignissim tempor');
INSERT INTO `team` (`id`,`name`) VALUES (432,'Auctor non, feugiat nec,');
INSERT INTO `team` (`id`,`name`) VALUES (433,'Magna sed dui. Fusce');
INSERT INTO `team` (`id`,`name`) VALUES (434,'Risus. Nulla eget metus');
INSERT INTO `team` (`id`,`name`) VALUES (435,'Fringilla, porttitor vulputate,');
INSERT INTO `team` (`id`,`name`) VALUES (436,'Dapibus id, blandit');
INSERT INTO `team` (`id`,`name`) VALUES (437,'Justo nec ante.');
INSERT INTO `team` (`id`,`name`) VALUES (438,'Lorem eu metus.');
INSERT INTO `team` (`id`,`name`) VALUES (439,'Sociosqu ad litora');
INSERT INTO `team` (`id`,`name`) VALUES (440,'Laoreet, libero et');
INSERT INTO `team` (`id`,`name`) VALUES (441,'Phasellus at augue');
INSERT INTO `team` (`id`,`name`) VALUES (442,'Nec luctus felis purus');
INSERT INTO `team` (`id`,`name`) VALUES (443,'Sed diam lorem,');
INSERT INTO `team` (`id`,`name`) VALUES (444,'Elit fermentum risus, at');
INSERT INTO `team` (`id`,`name`) VALUES (445,'Nascetur ridiculus mus.');
INSERT INTO `team` (`id`,`name`) VALUES (446,'Ut lacus. Nulla');
INSERT INTO `team` (`id`,`name`) VALUES (447,'Integer in magna.');
INSERT INTO `team` (`id`,`name`) VALUES (448,'Convallis ligula. Donec');
INSERT INTO `team` (`id`,`name`) VALUES (449,'Congue a, aliquet vel,');
INSERT INTO `team` (`id`,`name`) VALUES (450,'Lorem lorem, luctus');
INSERT INTO `team` (`id`,`name`) VALUES (451,'Aliquam nisl. Nulla eu');
INSERT INTO `team` (`id`,`name`) VALUES (452,'Sit amet ornare lectus');
INSERT INTO `team` (`id`,`name`) VALUES (453,'Mollis lectus pede et');
INSERT INTO `team` (`id`,`name`) VALUES (454,'Dictum eu, eleifend nec,');
INSERT INTO `team` (`id`,`name`) VALUES (455,'Lobortis augue scelerisque');
INSERT INTO `team` (`id`,`name`) VALUES (456,'Curabitur ut odio');
INSERT INTO `team` (`id`,`name`) VALUES (457,'Tortor, dictum eu,');
INSERT INTO `team` (`id`,`name`) VALUES (458,'Natoque penatibus et');
INSERT INTO `team` (`id`,`name`) VALUES (459,'Maecenas libero est, congue');
INSERT INTO `team` (`id`,`name`) VALUES (460,'Amet massa. Quisque porttitor');
INSERT INTO `team` (`id`,`name`) VALUES (461,'Fringilla est. Mauris eu');
INSERT INTO `team` (`id`,`name`) VALUES (462,'Faucibus. Morbi vehicula. Pellentesque');
INSERT INTO `team` (`id`,`name`) VALUES (463,'Vestibulum ante ipsum primis');
INSERT INTO `team` (`id`,`name`) VALUES (464,'Sit amet ante.');
INSERT INTO `team` (`id`,`name`) VALUES (465,'Et ultrices posuere');
INSERT INTO `team` (`id`,`name`) VALUES (466,'Quam dignissim pharetra.');
INSERT INTO `team` (`id`,`name`) VALUES (467,'Pede, malesuada vel, venenatis');
INSERT INTO `team` (`id`,`name`) VALUES (468,'Donec luctus aliquet');
INSERT INTO `team` (`id`,`name`) VALUES (469,'Erat. Vivamus nisi.');
INSERT INTO `team` (`id`,`name`) VALUES (470,'Magna. Suspendisse tristique');
INSERT INTO `team` (`id`,`name`) VALUES (471,'Ultrices. Duis volutpat');
INSERT INTO `team` (`id`,`name`) VALUES (472,'Sagittis. Nullam vitae');
INSERT INTO `team` (`id`,`name`) VALUES (473,'Accumsan neque et');
INSERT INTO `team` (`id`,`name`) VALUES (474,'Mauris blandit enim');
INSERT INTO `team` (`id`,`name`) VALUES (475,'Massa. Suspendisse eleifend. Cras');
INSERT INTO `team` (`id`,`name`) VALUES (476,'Et risus. Quisque libero');
INSERT INTO `team` (`id`,`name`) VALUES (477,'Morbi tristique senectus et');
INSERT INTO `team` (`id`,`name`) VALUES (478,'Habitant morbi tristique');
INSERT INTO `team` (`id`,`name`) VALUES (479,'Eu erat semper rutrum.');
INSERT INTO `team` (`id`,`name`) VALUES (480,'Et pede. Nunc');
INSERT INTO `team` (`id`,`name`) VALUES (481,'Nec tellus. Nunc lectus');
INSERT INTO `team` (`id`,`name`) VALUES (482,'Malesuada fringilla est. Mauris');
INSERT INTO `team` (`id`,`name`) VALUES (483,'Nonummy ipsum non');
INSERT INTO `team` (`id`,`name`) VALUES (484,'Velit. Pellentesque ultricies dignissim');
INSERT INTO `team` (`id`,`name`) VALUES (485,'Lacinia at, iaculis quis,');
INSERT INTO `team` (`id`,`name`) VALUES (486,'Orci. Ut semper pretium');
INSERT INTO `team` (`id`,`name`) VALUES (487,'Rutrum non, hendrerit id,');
INSERT INTO `team` (`id`,`name`) VALUES (488,'Consectetuer rhoncus. Nullam');
INSERT INTO `team` (`id`,`name`) VALUES (489,'Placerat. Cras dictum');
INSERT INTO `team` (`id`,`name`) VALUES (490,'Nec luctus felis');
INSERT INTO `team` (`id`,`name`) VALUES (491,'Non, egestas a, dui.');
INSERT INTO `team` (`id`,`name`) VALUES (492,'Maecenas malesuada fringilla est.');
INSERT INTO `team` (`id`,`name`) VALUES (493,'The Curvy Giraffes');
INSERT INTO `team` (`id`,`name`) VALUES (494,'Duis elementum, dui');
INSERT INTO `team` (`id`,`name`) VALUES (495,'Et ipsum cursus vestibulum.');
INSERT INTO `team` (`id`,`name`) VALUES (496,'Sem semper erat, in');
INSERT INTO `team` (`id`,`name`) VALUES (497,'Ultrices. Duis volutpat nunc');
INSERT INTO `team` (`id`,`name`) VALUES (498,'Sem molestie sodales. Mauris');
INSERT INTO `team` (`id`,`name`) VALUES (499,'Fringilla. Donec feugiat metus');
INSERT INTO `team` (`id`,`name`) VALUES (500,'Elit elit fermentum');
INSERT INTO `team` (`id`,`name`) VALUES (501,'Aliquam eu, accumsan sed,');
INSERT INTO `team` (`id`,`name`) VALUES (502,'Sagittis. Duis gravida.');
INSERT INTO `team` (`id`,`name`) VALUES (503,'Posuere cubilia Curae');
INSERT INTO `team` (`id`,`name`) VALUES (504,'Sapien molestie orci tincidunt');
INSERT INTO `team` (`id`,`name`) VALUES (505,'Libero est, congue');
INSERT INTO `team` (`id`,`name`) VALUES (506,'Praesent eu nulla at');
INSERT INTO `team` (`id`,`name`) VALUES (507,'Leo. Morbi neque tellus,');
INSERT INTO `team` (`id`,`name`) VALUES (508,'Massa. Mauris vestibulum,');
INSERT INTO `team` (`id`,`name`) VALUES (509,'Tellus, imperdiet non,');
INSERT INTO `team` (`id`,`name`) VALUES (510,'In ornare sagittis felis.');
INSERT INTO `team` (`id`,`name`) VALUES (511,'Elit, a feugiat tellus');
INSERT INTO `team` (`id`,`name`) VALUES (512,'Senectus et netus et');
INSERT INTO `team` (`id`,`name`) VALUES (513,'Justo faucibus lectus,');
INSERT INTO `team` (`id`,`name`) VALUES (514,'Massa rutrum magna. Cras');
INSERT INTO `team` (`id`,`name`) VALUES (515,'Neque vitae semper egestas,');
INSERT INTO `team` (`id`,`name`) VALUES (516,'Mollis. Phasellus libero');
INSERT INTO `team` (`id`,`name`) VALUES (517,'Nulla. Donec non justo.');
INSERT INTO `team` (`id`,`name`) VALUES (518,'Blandit enim consequat purus.');
INSERT INTO `team` (`id`,`name`) VALUES (519,'Fusce feugiat. Lorem ipsum');
INSERT INTO `team` (`id`,`name`) VALUES (520,'Interdum. Curabitur dictum.');
INSERT INTO `team` (`id`,`name`) VALUES (521,'Eros non enim commodo');
INSERT INTO `team` (`id`,`name`) VALUES (522,'Condimentum. Donec at arcu.');
INSERT INTO `team` (`id`,`name`) VALUES (523,'In molestie tortor');
INSERT INTO `team` (`id`,`name`) VALUES (524,'Vitae dolor. Donec');
INSERT INTO `team` (`id`,`name`) VALUES (525,'Sit amet, consectetuer');
INSERT INTO `team` (`id`,`name`) VALUES (526,'Cursus non, egestas a,');
INSERT INTO `team` (`id`,`name`) VALUES (527,'Ornare lectus justo eu');
INSERT INTO `team` (`id`,`name`) VALUES (528,'Etiam gravida molestie');
INSERT INTO `team` (`id`,`name`) VALUES (529,'Vitae velit egestas');
INSERT INTO `team` (`id`,`name`) VALUES (530,'Varius. Nam porttitor scelerisque');
INSERT INTO `team` (`id`,`name`) VALUES (531,'Metus. Vivamus euismod');
INSERT INTO `team` (`id`,`name`) VALUES (532,'Eu dolor egestas rhoncus.');
INSERT INTO `team` (`id`,`name`) VALUES (533,'Nulla. In tincidunt');
INSERT INTO `team` (`id`,`name`) VALUES (534,'Congue, elit sed consequat');
INSERT INTO `team` (`id`,`name`) VALUES (535,'Risus. Donec egestas.');
INSERT INTO `team` (`id`,`name`) VALUES (536,'Nullam vitae diam. Proin');
INSERT INTO `team` (`id`,`name`) VALUES (537,'Mauris id sapien.');
INSERT INTO `team` (`id`,`name`) VALUES (538,'Risus. Duis a');
INSERT INTO `team` (`id`,`name`) VALUES (539,'Egestas ligula. Nullam');
INSERT INTO `team` (`id`,`name`) VALUES (540,'Sagittis augue, eu tempor');
INSERT INTO `team` (`id`,`name`) VALUES (541,'Nec, leo. Morbi neque');
INSERT INTO `team` (`id`,`name`) VALUES (542,'Euismod mauris eu');
INSERT INTO `team` (`id`,`name`) VALUES (543,'Quisque porttitor eros');
INSERT INTO `team` (`id`,`name`) VALUES (544,'Tristique neque venenatis lacus.');
INSERT INTO `team` (`id`,`name`) VALUES (545,'Ligula elit, pretium et,');
INSERT INTO `team` (`id`,`name`) VALUES (546,'Ullamcorper viverra. Maecenas');
INSERT INTO `team` (`id`,`name`) VALUES (547,'Donec est. Nunc');
INSERT INTO `team` (`id`,`name`) VALUES (548,'Sapien imperdiet ornare. In');
INSERT INTO `team` (`id`,`name`) VALUES (549,'Nunc sollicitudin commodo ipsum.');
INSERT INTO `team` (`id`,`name`) VALUES (550,'Dolor dolor, tempus');
INSERT INTO `team` (`id`,`name`) VALUES (551,'Eu, placerat eget,');
INSERT INTO `team` (`id`,`name`) VALUES (552,'Dolor, tempus non,');
INSERT INTO `team` (`id`,`name`) VALUES (553,'Auctor vitae, aliquet');
INSERT INTO `team` (`id`,`name`) VALUES (554,'Augue, eu tempor erat');
INSERT INTO `team` (`id`,`name`) VALUES (555,'A, facilisis non, bibendum');
INSERT INTO `team` (`id`,`name`) VALUES (556,'Accumsan interdum libero');
INSERT INTO `team` (`id`,`name`) VALUES (557,'Turpis. In condimentum. Donec');
INSERT INTO `team` (`id`,`name`) VALUES (558,'Tellus faucibus leo, in');
INSERT INTO `team` (`id`,`name`) VALUES (559,'Eu sem. Pellentesque ut');
INSERT INTO `team` (`id`,`name`) VALUES (560,'Arcu. Vestibulum ante');
INSERT INTO `team` (`id`,`name`) VALUES (561,'Ullamcorper magna. Sed');
INSERT INTO `team` (`id`,`name`) VALUES (562,'Dolor dapibus gravida. Aliquam');
INSERT INTO `team` (`id`,`name`) VALUES (563,'Ullamcorper, velit in aliquet');
INSERT INTO `team` (`id`,`name`) VALUES (564,'Nam interdum enim');
INSERT INTO `team` (`id`,`name`) VALUES (565,'Vel quam dignissim');
INSERT INTO `team` (`id`,`name`) VALUES (566,'Quisque libero lacus,');
INSERT INTO `team` (`id`,`name`) VALUES (567,'Felis purus ac');
INSERT INTO `team` (`id`,`name`) VALUES (568,'The Colorful Ostriches');
INSERT INTO `team` (`id`,`name`) VALUES (569,'Dictum magna. Ut tincidunt');
INSERT INTO `team` (`id`,`name`) VALUES (570,'Nulla magna, malesuada');
INSERT INTO `team` (`id`,`name`) VALUES (571,'Per inceptos hymenaeos. Mauris');
INSERT INTO `team` (`id`,`name`) VALUES (572,'Eu metus. In lorem.');
INSERT INTO `team` (`id`,`name`) VALUES (573,'Nec tempus mauris erat');
INSERT INTO `team` (`id`,`name`) VALUES (574,'Nam consequat dolor');
INSERT INTO `team` (`id`,`name`) VALUES (575,'Mi pede, nonummy ut,');
INSERT INTO `team` (`id`,`name`) VALUES (576,'Lectus, a sollicitudin orci');
INSERT INTO `team` (`id`,`name`) VALUES (577,'Nisi sem semper');
INSERT INTO `team` (`id`,`name`) VALUES (578,'Lorem vitae odio');
INSERT INTO `team` (`id`,`name`) VALUES (579,'Augue ut lacus. Nulla');
INSERT INTO `team` (`id`,`name`) VALUES (580,'Commodo tincidunt nibh.');
INSERT INTO `team` (`id`,`name`) VALUES (581,'Proin sed turpis nec');
INSERT INTO `team` (`id`,`name`) VALUES (582,'Est ac mattis semper,');
INSERT INTO `team` (`id`,`name`) VALUES (583,'Class aptent taciti sociosqu');
INSERT INTO `team` (`id`,`name`) VALUES (584,'Venenatis vel, faucibus');
INSERT INTO `team` (`id`,`name`) VALUES (585,'Tempor arcu. Vestibulum');
INSERT INTO `team` (`id`,`name`) VALUES (586,'Ornare egestas ligula. Nullam');
INSERT INTO `team` (`id`,`name`) VALUES (587,'Urna convallis erat, eget');
INSERT INTO `team` (`id`,`name`) VALUES (588,'Faucibus leo, in');
INSERT INTO `team` (`id`,`name`) VALUES (589,'Dolor. Donec fringilla. Donec');
INSERT INTO `team` (`id`,`name`) VALUES (590,'Est. Mauris eu turpis.');
INSERT INTO `team` (`id`,`name`) VALUES (591,'Ultrices a, auctor non,');
INSERT INTO `team` (`id`,`name`) VALUES (592,'Ornare, libero at auctor');
INSERT INTO `team` (`id`,`name`) VALUES (593,'Non arcu. Vivamus sit');
INSERT INTO `team` (`id`,`name`) VALUES (594,'Mauris quis turpis vitae');
INSERT INTO `team` (`id`,`name`) VALUES (595,'Tristique pellentesque, tellus');
INSERT INTO `team` (`id`,`name`) VALUES (596,'Neque sed dictum');
INSERT INTO `team` (`id`,`name`) VALUES (597,'Sociis natoque penatibus');
INSERT INTO `team` (`id`,`name`) VALUES (598,'Lobortis quis, pede.');
INSERT INTO `team` (`id`,`name`) VALUES (599,'Semper et, lacinia vitae,');
INSERT INTO `team` (`id`,`name`) VALUES (600,'Vel, convallis in,');
INSERT INTO `team` (`id`,`name`) VALUES (601,'At, iaculis quis, pede.');
INSERT INTO `team` (`id`,`name`) VALUES (602,'Morbi non sapien');
INSERT INTO `team` (`id`,`name`) VALUES (603,'Massa non ante bibendum');
INSERT INTO `team` (`id`,`name`) VALUES (604,'Libero est, congue a,');
INSERT INTO `team` (`id`,`name`) VALUES (605,'Eget varius ultrices, mauris');
INSERT INTO `team` (`id`,`name`) VALUES (606,'Pede nec ante blandit');
INSERT INTO `team` (`id`,`name`) VALUES (607,'Gravida sit amet, dapibus');
INSERT INTO `team` (`id`,`name`) VALUES (608,'Mus. Aenean eget');
INSERT INTO `team` (`id`,`name`) VALUES (609,'Enim commodo hendrerit.');
INSERT INTO `team` (`id`,`name`) VALUES (610,'Lorem tristique aliquet. Phasellus');
INSERT INTO `team` (`id`,`name`) VALUES (611,'Vitae, erat. Vivamus nisi.');
INSERT INTO `team` (`id`,`name`) VALUES (612,'Non, lacinia at,');
INSERT INTO `team` (`id`,`name`) VALUES (613,'Magna a tortor. Nunc');
INSERT INTO `team` (`id`,`name`) VALUES (614,'Dictum cursus. Nunc mauris');
INSERT INTO `team` (`id`,`name`) VALUES (615,'Tempus scelerisque, lorem');
INSERT INTO `team` (`id`,`name`) VALUES (616,'Donec vitae erat');
INSERT INTO `team` (`id`,`name`) VALUES (617,'Sed dictum. Proin eget');
INSERT INTO `team` (`id`,`name`) VALUES (618,'Sagittis placerat. Cras dictum');
INSERT INTO `team` (`id`,`name`) VALUES (619,'Semper erat, in');
INSERT INTO `team` (`id`,`name`) VALUES (620,'Ut, sem. Nulla interdum.');
INSERT INTO `team` (`id`,`name`) VALUES (621,'Neque tellus, imperdiet');
INSERT INTO `team` (`id`,`name`) VALUES (622,'Tristique neque venenatis');
INSERT INTO `team` (`id`,`name`) VALUES (623,'Duis risus odio, auctor');
INSERT INTO `team` (`id`,`name`) VALUES (624,'Lorem, luctus ut, pellentesque');
INSERT INTO `team` (`id`,`name`) VALUES (625,'Bibendum. Donec felis');
INSERT INTO `team` (`id`,`name`) VALUES (626,'Id sapien. Cras dolor');
INSERT INTO `team` (`id`,`name`) VALUES (627,'Nisl elementum purus, accumsan');
INSERT INTO `team` (`id`,`name`) VALUES (628,'Rutrum, justo. Praesent');
INSERT INTO `team` (`id`,`name`) VALUES (629,'Risus quis diam');
INSERT INTO `team` (`id`,`name`) VALUES (630,'Ridiculus mus. Aenean');
INSERT INTO `team` (`id`,`name`) VALUES (631,'Amet, risus. Donec nibh');
INSERT INTO `team` (`id`,`name`) VALUES (632,'Amet lorem semper');
INSERT INTO `team` (`id`,`name`) VALUES (633,'Vulputate, posuere vulputate, lacus.');
INSERT INTO `team` (`id`,`name`) VALUES (634,'Aliquet. Phasellus fermentum');
INSERT INTO `team` (`id`,`name`) VALUES (635,'Eget metus. In');
INSERT INTO `team` (`id`,`name`) VALUES (636,'Cras interdum. Nunc');
INSERT INTO `team` (`id`,`name`) VALUES (637,'Cursus purus. Nullam');
INSERT INTO `team` (`id`,`name`) VALUES (638,'Cursus et, magna. Praesent');
INSERT INTO `team` (`id`,`name`) VALUES (639,'Scelerisque dui. Suspendisse');
INSERT INTO `team` (`id`,`name`) VALUES (640,'Justo. Proin non massa');
INSERT INTO `team` (`id`,`name`) VALUES (641,'In felis. Nulla');
INSERT INTO `team` (`id`,`name`) VALUES (642,'Molestie in, tempus');
INSERT INTO `team` (`id`,`name`) VALUES (643,'Pretium neque. Morbi');
INSERT INTO `team` (`id`,`name`) VALUES (644,'Nulla dignissim. Maecenas');
INSERT INTO `team` (`id`,`name`) VALUES (645,'Arcu. Morbi sit amet');
INSERT INTO `team` (`id`,`name`) VALUES (646,'Aliquet lobortis, nisi');
INSERT INTO `team` (`id`,`name`) VALUES (647,'Pellentesque habitant morbi');
INSERT INTO `team` (`id`,`name`) VALUES (648,'Aliquam gravida mauris');
INSERT INTO `team` (`id`,`name`) VALUES (649,'Pede. Suspendisse dui. Fusce');
INSERT INTO `team` (`id`,`name`) VALUES (650,'Duis cursus, diam at');
INSERT INTO `team` (`id`,`name`) VALUES (651,'Porttitor tellus non');
INSERT INTO `team` (`id`,`name`) VALUES (652,'Fusce mollis. Duis');
INSERT INTO `team` (`id`,`name`) VALUES (653,'Nibh lacinia orci, consectetuer');
INSERT INTO `team` (`id`,`name`) VALUES (654,'Egestas blandit. Nam');
INSERT INTO `team` (`id`,`name`) VALUES (655,'Primis in faucibus');
INSERT INTO `team` (`id`,`name`) VALUES (656,'Mollis. Duis sit');
INSERT INTO `team` (`id`,`name`) VALUES (657,'At, velit. Pellentesque');
INSERT INTO `team` (`id`,`name`) VALUES (658,'Elit, pellentesque a,');
INSERT INTO `team` (`id`,`name`) VALUES (659,'Consectetuer rhoncus. Nullam velit');
INSERT INTO `team` (`id`,`name`) VALUES (660,'Sodales. Mauris blandit');
INSERT INTO `team` (`id`,`name`) VALUES (661,'Nulla. In tincidunt congue');
INSERT INTO `team` (`id`,`name`) VALUES (662,'Sed sem egestas blandit.');
INSERT INTO `team` (`id`,`name`) VALUES (663,'Lacinia orci, consectetuer');
INSERT INTO `team` (`id`,`name`) VALUES (664,'Montes, nascetur ridiculus mus.');
INSERT INTO `team` (`id`,`name`) VALUES (665,'Rhoncus. Nullam velit dui,');
INSERT INTO `team` (`id`,`name`) VALUES (666,'Scelerisque neque. Nullam');
INSERT INTO `team` (`id`,`name`) VALUES (667,'Non, hendrerit id,');
INSERT INTO `team` (`id`,`name`) VALUES (668,'Lectus pede et risus.');
INSERT INTO `team` (`id`,`name`) VALUES (669,'Augue ac ipsum.');
INSERT INTO `team` (`id`,`name`) VALUES (670,'Cras eu tellus');
INSERT INTO `team` (`id`,`name`) VALUES (671,'Velit. Sed malesuada augue');
INSERT INTO `team` (`id`,`name`) VALUES (672,'Etiam gravida molestie arcu.');
INSERT INTO `team` (`id`,`name`) VALUES (673,'Donec vitae erat vel');
INSERT INTO `team` (`id`,`name`) VALUES (674,'Aliquam fringilla cursus purus.');
INSERT INTO `team` (`id`,`name`) VALUES (675,'Tempus, lorem fringilla ornare');
INSERT INTO `team` (`id`,`name`) VALUES (676,'Amet luctus vulputate,');
INSERT INTO `team` (`id`,`name`) VALUES (677,'Iaculis, lacus pede');
INSERT INTO `team` (`id`,`name`) VALUES (678,'Lectus rutrum urna,');
INSERT INTO `team` (`id`,`name`) VALUES (679,'Per inceptos hymenaeos.');
INSERT INTO `team` (`id`,`name`) VALUES (680,'Pretium aliquet, metus');
INSERT INTO `team` (`id`,`name`) VALUES (681,'Integer vitae nibh. Donec');
INSERT INTO `team` (`id`,`name`) VALUES (682,'Turpis egestas. Fusce aliquet');
INSERT INTO `team` (`id`,`name`) VALUES (683,'Nulla. Integer urna.');
INSERT INTO `team` (`id`,`name`) VALUES (684,'Mattis velit justo');
INSERT INTO `team` (`id`,`name`) VALUES (685,'Semper pretium neque.');
INSERT INTO `team` (`id`,`name`) VALUES (686,'Nunc ac mattis ornare,');
INSERT INTO `team` (`id`,`name`) VALUES (687,'Hendrerit. Donec porttitor tellus');
INSERT INTO `team` (`id`,`name`) VALUES (688,'Accumsan interdum libero dui');
INSERT INTO `team` (`id`,`name`) VALUES (689,'Eget nisi dictum augue');
INSERT INTO `team` (`id`,`name`) VALUES (690,'Egestas. Duis ac arcu.');
INSERT INTO `team` (`id`,`name`) VALUES (691,'Vel pede blandit congue.');
INSERT INTO `team` (`id`,`name`) VALUES (692,'Proin vel arcu');
INSERT INTO `team` (`id`,`name`) VALUES (693,'Ridiculus mus. Donec');
INSERT INTO `team` (`id`,`name`) VALUES (694,'Montes, nascetur ridiculus');
INSERT INTO `team` (`id`,`name`) VALUES (695,'Non, lobortis quis,');
INSERT INTO `team` (`id`,`name`) VALUES (696,'Arcu. Sed eu');
INSERT INTO `team` (`id`,`name`) VALUES (697,'Adipiscing fringilla, porttitor');
INSERT INTO `team` (`id`,`name`) VALUES (698,'A mi fringilla mi');
INSERT INTO `team` (`id`,`name`) VALUES (699,'Nec, malesuada ut,');
INSERT INTO `team` (`id`,`name`) VALUES (700,'Aliquam erat volutpat. Nulla');
INSERT INTO `team` (`id`,`name`) VALUES (701,'Lorem, vehicula et, rutrum');
INSERT INTO `team` (`id`,`name`) VALUES (702,'Dapibus quam quis diam.');
INSERT INTO `team` (`id`,`name`) VALUES (703,'Nulla interdum. Curabitur');
INSERT INTO `team` (`id`,`name`) VALUES (704,'Mi felis, adipiscing fringilla,');
INSERT INTO `team` (`id`,`name`) VALUES (705,'Donec est mauris,');
INSERT INTO `team` (`id`,`name`) VALUES (706,'Proin vel nisl. Quisque');
INSERT INTO `team` (`id`,`name`) VALUES (707,'Erat nonummy ultricies');
INSERT INTO `team` (`id`,`name`) VALUES (708,'Aenean sed pede');
INSERT INTO `team` (`id`,`name`) VALUES (709,'Ultricies ligula. Nullam enim.');
INSERT INTO `team` (`id`,`name`) VALUES (710,'The Cooperative Panthers');
INSERT INTO `team` (`id`,`name`) VALUES (711,'Eget massa. Suspendisse eleifend.');
INSERT INTO `team` (`id`,`name`) VALUES (712,'At sem molestie sodales.');
INSERT INTO `team` (`id`,`name`) VALUES (713,'Quis, pede. Praesent eu');
INSERT INTO `team` (`id`,`name`) VALUES (714,'Quis, tristique ac,');
INSERT INTO `team` (`id`,`name`) VALUES (715,'Quisque imperdiet, erat nonummy');
INSERT INTO `team` (`id`,`name`) VALUES (716,'Sem elit, pharetra ut,');
INSERT INTO `team` (`id`,`name`) VALUES (717,'Faucibus leo, in lobortis');
INSERT INTO `team` (`id`,`name`) VALUES (718,'Vehicula. Pellentesque tincidunt');
INSERT INTO `team` (`id`,`name`) VALUES (719,'Adipiscing elit. Curabitur sed');
INSERT INTO `team` (`id`,`name`) VALUES (720,'Diam at pretium aliquet,');
INSERT INTO `team` (`id`,`name`) VALUES (721,'Ac urna. Ut tincidunt');
INSERT INTO `team` (`id`,`name`) VALUES (722,'Vestibulum nec, euismod in,');
INSERT INTO `team` (`id`,`name`) VALUES (723,'Congue. In scelerisque scelerisque');
INSERT INTO `team` (`id`,`name`) VALUES (724,'Ligula elit, pretium');
INSERT INTO `team` (`id`,`name`) VALUES (725,'Arcu ac orci. Ut');
INSERT INTO `team` (`id`,`name`) VALUES (726,'Sit amet orci.');
INSERT INTO `team` (`id`,`name`) VALUES (727,'Sed molestie. Sed');
INSERT INTO `team` (`id`,`name`) VALUES (728,'Tellus. Aenean egestas');
INSERT INTO `team` (`id`,`name`) VALUES (729,'Felis purus ac tellus.');
INSERT INTO `team` (`id`,`name`) VALUES (730,'Aliquam rutrum lorem ac');
INSERT INTO `team` (`id`,`name`) VALUES (731,'Dolor quam, elementum');
INSERT INTO `team` (`id`,`name`) VALUES (732,'Purus mauris a');
INSERT INTO `team` (`id`,`name`) VALUES (733,'Aliquam vulputate ullamcorper magna.');
INSERT INTO `team` (`id`,`name`) VALUES (734,'Curabitur consequat, lectus sit');
INSERT INTO `team` (`id`,`name`) VALUES (735,'Tempus eu, ligula.');
INSERT INTO `team` (`id`,`name`) VALUES (736,'Eget ipsum. Suspendisse');
INSERT INTO `team` (`id`,`name`) VALUES (737,'Semper tellus id');
INSERT INTO `team` (`id`,`name`) VALUES (738,'Tincidunt, nunc ac mattis');
INSERT INTO `team` (`id`,`name`) VALUES (739,'Curabitur vel lectus.');
INSERT INTO `team` (`id`,`name`) VALUES (740,'Velit. Quisque varius. Nam');
INSERT INTO `team` (`id`,`name`) VALUES (741,'Integer id magna et');
INSERT INTO `team` (`id`,`name`) VALUES (742,'Elit. Nulla facilisi.');
INSERT INTO `team` (`id`,`name`) VALUES (743,'At, egestas a,');
INSERT INTO `team` (`id`,`name`) VALUES (744,'Commodo ipsum. Suspendisse non');
INSERT INTO `team` (`id`,`name`) VALUES (745,'Sed nunc est,');
INSERT INTO `team` (`id`,`name`) VALUES (746,'Nunc lectus pede,');
INSERT INTO `team` (`id`,`name`) VALUES (747,'Tempor erat neque');
INSERT INTO `team` (`id`,`name`) VALUES (748,'Tincidunt congue turpis. In');
INSERT INTO `team` (`id`,`name`) VALUES (749,'Orci quis lectus.');
INSERT INTO `team` (`id`,`name`) VALUES (750,'Ut nec urna');
INSERT INTO `team` (`id`,`name`) VALUES (751,'Semper egestas, urna justo');
INSERT INTO `team` (`id`,`name`) VALUES (752,'A felis ullamcorper viverra.');
INSERT INTO `team` (`id`,`name`) VALUES (753,'Neque. Nullam ut nisi');
INSERT INTO `team` (`id`,`name`) VALUES (754,'Lacus. Cras interdum.');
INSERT INTO `team` (`id`,`name`) VALUES (755,'Ipsum. Suspendisse non leo.');
INSERT INTO `team` (`id`,`name`) VALUES (756,'Arcu imperdiet ullamcorper.');
INSERT INTO `team` (`id`,`name`) VALUES (757,'Hendrerit id, ante. Nunc');
INSERT INTO `team` (`id`,`name`) VALUES (758,'Mauris eu turpis. Nulla');
INSERT INTO `team` (`id`,`name`) VALUES (759,'Dolor sit amet,');
INSERT INTO `team` (`id`,`name`) VALUES (760,'Id, mollis nec, cursus');
INSERT INTO `team` (`id`,`name`) VALUES (761,'Ante dictum cursus.');
INSERT INTO `team` (`id`,`name`) VALUES (762,'Neque. Nullam nisl. Maecenas');
INSERT INTO `team` (`id`,`name`) VALUES (763,'Dictum eu, eleifend');
INSERT INTO `team` (`id`,`name`) VALUES (764,'Libero. Integer in');
INSERT INTO `team` (`id`,`name`) VALUES (765,'Justo eu arcu. Morbi');
INSERT INTO `team` (`id`,`name`) VALUES (766,'Eget, dictum placerat,');
INSERT INTO `team` (`id`,`name`) VALUES (767,'Egestas. Fusce aliquet magna');
INSERT INTO `team` (`id`,`name`) VALUES (768,'Vestibulum accumsan neque et');
INSERT INTO `team` (`id`,`name`) VALUES (769,'Diam lorem, auctor');
INSERT INTO `team` (`id`,`name`) VALUES (770,'Mauris. Suspendisse aliquet molestie');
INSERT INTO `team` (`id`,`name`) VALUES (771,'Aliquam nec enim. Nunc');
INSERT INTO `team` (`id`,`name`) VALUES (772,'Malesuada malesuada. Integer');
INSERT INTO `team` (`id`,`name`) VALUES (773,'Est mauris, rhoncus');
INSERT INTO `team` (`id`,`name`) VALUES (774,'Mauris magna. Duis dignissim');
INSERT INTO `team` (`id`,`name`) VALUES (775,'Non justo. Proin');
INSERT INTO `team` (`id`,`name`) VALUES (776,'Gravida. Aliquam tincidunt,');
INSERT INTO `team` (`id`,`name`) VALUES (777,'Metus. In nec');
INSERT INTO `team` (`id`,`name`) VALUES (778,'Orci luctus et');
INSERT INTO `team` (`id`,`name`) VALUES (779,'Enim nisl elementum');
INSERT INTO `team` (`id`,`name`) VALUES (780,'Curabitur sed tortor. Integer');
INSERT INTO `team` (`id`,`name`) VALUES (781,'At augue id');
INSERT INTO `team` (`id`,`name`) VALUES (782,'Habitant morbi tristique senectus');
INSERT INTO `team` (`id`,`name`) VALUES (783,'Urna. Nullam lobortis quam');
INSERT INTO `team` (`id`,`name`) VALUES (784,'Tempus eu, ligula. Aenean');
INSERT INTO `team` (`id`,`name`) VALUES (785,'Auctor non, feugiat');
INSERT INTO `team` (`id`,`name`) VALUES (786,'Lorem ipsum dolor sit');
INSERT INTO `team` (`id`,`name`) VALUES (787,'Odio. Aliquam vulputate ullamcorper');
INSERT INTO `team` (`id`,`name`) VALUES (788,'Amet, consectetuer adipiscing');
INSERT INTO `team` (`id`,`name`) VALUES (789,'At risus. Nunc ac');
INSERT INTO `team` (`id`,`name`) VALUES (790,'Libero. Donec consectetuer');
INSERT INTO `team` (`id`,`name`) VALUES (791,'Aliquam arcu. Aliquam');
INSERT INTO `team` (`id`,`name`) VALUES (792,'Vitae dolor. Donec fringilla.');
INSERT INTO `team` (`id`,`name`) VALUES (793,'Tellus non magna.');
INSERT INTO `team` (`id`,`name`) VALUES (794,'Malesuada. Integer id magna');
INSERT INTO `team` (`id`,`name`) VALUES (795,'Taciti sociosqu ad');
INSERT INTO `team` (`id`,`name`) VALUES (796,'Nunc ut erat.');
INSERT INTO `team` (`id`,`name`) VALUES (797,'Phasellus at augue id');
INSERT INTO `team` (`id`,`name`) VALUES (798,'Id risus quis');
INSERT INTO `team` (`id`,`name`) VALUES (799,'Diam vel arcu.');
INSERT INTO `team` (`id`,`name`) VALUES (800,'Aenean egestas hendrerit neque.');